website/auth.py
from argparse import REMAINDER
from flask import Blueprint, render_template,flash,url_for,request, make_response, redirect, Flask, session
from tkinter import messagebox
from flask_paginate import Pagination, get_page_parameter
import psycopg2
import json
import base64


def alert(title, message, kind='info', hidemain=True):
    if kind not in ('error', 'warning', 'info'):
        raise ValueError('Unsupported alert kind.')

    show_method = getattr(messagebox, 'show{}'.format(kind))
    show_method(title, message)

auth = Blueprint('auth', __name__)

@auth.route('/home', methods=['POST', 'GET'])
def home():
        email = session[session['userid']]['email']
        if email:
                return render_template('home.html', email = email)
        else:
                return render_template('home.html')
        
@auth.route('/homeAdm', methods=['post', 'get'])
def homeAdm():
    return render_template('homeAdm.html')

@auth.route('/login',methods=['GET', 'POST'])
def login():
    if request.method=='POST':
         email = request.form.get('email')
         password1 = request.form.get('password1')
         print(email)
         print(password1)
         if email == 'admin@admin' and password1 == 'admin':
                return redirect(url_for('auth.homeAdm'))
         conn = psycopg2.connect("postgresql://postgres:postgres2@localhost:5432/licenta_db")
         crsr = conn.cursor()
         crsr.execute("select email,password1,userid from Users where email=%(email)s and password1=%(password1)s", {'email': email, 'password1': password1})
         data = crsr.fetchall()
         if not email and not password1:
            flash('Trebuie să completați câmpurile!', category='error')
         elif not email and password1:
                flash('Trebuie să introduceți email-ul!', category='error')
         elif not password1 and email:
                flash('Trebuie să introduceți parola!', category='error')
         elif crsr.fetchall() is None:
                flash('Credențialele introduse nu sunt corecte!', category='error')     
         else:
                user_id = str(data[0][2])
                session['userid'] = user_id
                if user_id not in session:
                      session[user_id] = {'email': email, 'lista_filme': [], 'filme_neprelucrate': [],
                                    'lista_seriale': [], 'seriale_neprelucrate': []}
                if email not in session:
                      session[email] = True
                      flash('V-ați logat cu succes!', category='success')
                      return redirect(url_for("auth.formular"))
                return redirect(url_for("auth.formular_rezultate"))
         crsr.close()
         conn.close()
    return render_template("login.html")


@auth.route('/logout', methods = ['GET', 'POST'])
def logout():
     session.pop('email', None)
     return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        print(email)
        print(firstName)
        print(password1)
        print(password2)
        
        conn = psycopg2.connect("postgresql://postgres:postgres2@localhost:5432/licenta_db")
        crsr = conn.cursor()
        crsr.execute("select email,firstName,password1 from Users where email=%(email)s and firstName=%(firstName)s and password1 = %(password1)s", {'email': email, 'firstName' : firstName, 'password1':password1})
        
        if email is not None and len(email) < 4:
                flash('Email-ul trebuie să aibă mai mult de 3 caractere!', category = 'error')
        elif firstName is not None and len(firstName) <2:
                flash('Prenumele trebuie să aibă mai mult de un caracter!',category = 'error')     
        elif  password1 != password2:
                flash('Parolele nu se potrivesc', category = 'error')
        elif password1 is not None and  len(password1) <7:
                flash('Parola trebuie să aibă cel puțin 7 caractere!', category = 'error')
      

        else:
                flash('Cont creat cu succes!', category = 'success')
                crsr = conn.cursor()
                crsr.execute("insert into Users(email,firstName,password1) VALUES(%(email)s,%(firstName)s, %(password1)s)", {'email': email,'firstName':firstName, 'password1': password1}) 
                conn.commit()
                crsr.close()
                conn.close()
                #return render_template('login.html')    
    return render_template("sign_up.html") 

@auth.route('/formular', methods=['GET', 'POST'])
def formular():
    if request.method == 'POST':
        session.permanent = True
        conn = psycopg2.connect("postgresql://postgres:postgres2@localhost:5432/licenta_db")
        crsr2 = conn.cursor()
        crsr3 = conn.cursor()
        crsr4 = conn.cursor()
        crsr5 = conn.cursor()
        crsr6 = conn.cursor()
        crsr7 = conn.cursor()
        gen = request.form.getlist('gen_favorit')
        an_aparitie = request.form.getlist('an_favorit')

        an_aparitie_int = []
        for an in an_aparitie:
            an_int = int(an)
            an_aparitie_int.append(an_int)

        actor = request.form.getlist('actor_favorit')
        categorie_varsta = request.form.getlist('categ_fav')
        print(gen)
        print(an_aparitie)
        print(actor)
        print(categorie_varsta)

        listaux = []
        if len(gen) == 3:
                listaux.append(gen[0])
                listaux.append(gen[1])
                listaux.append(gen[2])
        elif len(gen) == 2:
                listaux.append(gen[0])
                listaux.append(gen[1])
                listaux.append('None')
        elif len(gen) == 1: 
                listaux.append(gen[0])
                listaux.append('None')
                listaux.append('None')
        else:
                listaux.append('None')
                listaux.append('None')
                listaux.append('None')
                #flash('Nu a fost selectat niciun gen !', category = 'error')

        print(listaux)
        
       # crsr.execute("SELECT * FROM Filme F JOIN FilmeGenuri FG ON F.genid = FG.genid JOIN Genuri G ON FG.genid = G.genid JOIN Actori A ON F.actorid = A.actorid JOIN FilmeActori FA ON A.actorid = FA.actorid WHERE (F.genid=%(gen1)s or F.genid=%(gen2)s or F.genid=%(gen3)s) and (F.an_aparitie=%(an_aparitie1)s or F.an_aparitie=%(an_aparitie2)s or F.an_aparitie=%(an_aparitie3)s)  and (A.actorid=%(actor1)s or A.actorid=%(actor2)s or A.actorid=%(actor3)s or A.actorid=%(actor4)s or A.actorid=%(actor5)s) and (F.categorie_varsta=%(categorie_varsta1)s or F.categorie_varsta=%(categorie_varsta2)s )",{'gen1': gen[0],'gen2': gen[1],'gen3': gen[2],'an_aparitie1': an_aparitie[0],'an_aparitie2': an_aparitie[1], 'an_aparitie3':an_aparitie[2],'actor1': actor[0], 'actor2': actor[1],'actor3': actor[2],'actor4': actor[3],'actor5': actor[4] ,'categorie_varsta1':categorie_varsta[0],'categorie_varsta2':categorie_varsta[1] })
        crsr2.execute("SELECT genid from genuri WHERE (numegen = %(gen1)s or numegen = %(gen2)s or numegen = %(gen3)s)", {'gen1': listaux[0], 'gen2':listaux[1], 'gen3':listaux[2]})
        id_tuple=crsr2.fetchall()
        if id_tuple:
            if len(gen) == 3 :
                id_value1 = str(id_tuple[0][0])
                id_value2 = str(id_tuple[1][0])
                id_value3 = str(id_tuple[2][0])
            elif len(gen) == 2 :
                id_value1 = str(id_tuple[0][0])
                id_value2 = str(id_tuple[1][0])
                id_value3 = 0
            elif len(gen) == 1:
                id_value1 = str(id_tuple[0][0])
                id_value2 = 0
                id_value3 = 0
        else:
                id_value1 = 0
                id_value2 = 0
                id_value3 = 0
                flash('Nu fost selectat niciun gen ! Nu s-au găsit rezultate!', category = 'error')
                return render_template('formular_rezultate.html')
               


        listaux2 = []
        if len(actor) == 5:
                listaux2.append(actor[0])
                listaux2.append(actor[1])
                listaux2.append(actor[2])
                listaux2.append(actor[3])
                listaux2.append(actor[4])
        elif len(actor) == 4:
                listaux2.append(actor[0])
                listaux2.append(actor[1])
                listaux2.append(actor[2])
                listaux2.append(actor[3])
                listaux2.append('None')
        elif len(actor) == 3: 
                listaux2.append(actor[0])
                listaux2.append(actor[1])
                listaux2.append(actor[2])
                listaux2.append('None')
                listaux2.append('None')
        elif len(actor) == 2: 
                listaux2.append(actor[0])
                listaux2.append(actor[1])
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None')
        elif len(actor) == 1: 
                listaux2.append(actor[0])
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None')              
        else:
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None')
                listaux2.append('None') 
                print('n-a fost selectat nimic la actor')

        print(listaux2)
        

website/templates/addMovie.html
<title>{% block title  %}Adăugare film{% endblock %}</title>
 <!DOCTYPE html>
 <html>
 <head>
    
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Adăugare film</title> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> 
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
            integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
            crossorigin="anonymous"
        />
        <link

    <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" 
    crossorigin="anonymous">
    </script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/css/styles.css" rel="stylesheet" /> 

        <style>
            body {
              background-image: url('/static/image.png');
              background-repeat: no-repeat;
              background-size: cover;
              
            }
          </style> 
         
    
</head>



<body id="page-top">
    <br> 
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error'%}
                    <div class="alert alert-danger alert-dismissible fade show">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         {{ message }}
                        
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}      
    </body>
<body>

  <div style="position:relative;margin:20px">  
    <label id="description-label1"><b>Introduceți informațiile noului film:</b></label><br><br>
    <form id="movie-form" action="/addMovie" method="POST" enctype="multipart/form-data">
        <label id="id-label"><b>Introduceți ID-ul filmului:</b></label><br>
        <input type="text" class="transparent-button"  name="idName" required><br><br>

        <label id="titlu-label"><b>Introduceți numele filmului:</b></label><br>
        <input type="text" class="transparent-button" name="movieName" required><br><br>

        <label id="descriere-label"><b>Introduceți paragraful cu descrierea:</b></label><br>
        <textarea name="descrName" class="transparent-button" required></textarea><br><br>

        <label id="dur-label"><b>Durata filmului:</b></label><br>
        <input name="durName" class="transparent-button" required></input><br><br>

        <label id="an-label"><b>Anul apariției filmului:</b></label><br>
        <input name="anName" class="transparent-button" required></input><br><br>

        <label id="categ-label"><b>Categoria de vârstă potrivită filmului:</b></label><br>
        <input name="categName" class="transparent-button" required></input><br><br>

        <label id="act-label"><b>Actorul principal al filmului (introduceți id-ul din listă):</b></label><br>
        <input name="actName" class="transparent-button" required></input><br><br>

        <table>
            <thead>
                <tr>
                    <th>Actor ID </th>
                    <th>Nume Prenume</th>
                </tr>
            </thead>
            <tbody>
                {% for actor in actori %}
                <tr>
                    <td>{{ actor[0] }}</td>
                    <td>{{ actor[1] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <label id="image-label"><b>Alegeți coperta filmului: </b></label><br>   
        <input type="file" name="filmPhoto" accept="image/*" required><br><br>

        <label id="gen-label"><b>Genul filmului (introduceți id-ul din listă):</b></label><br>
        <input name="genName" class="transparent-button" required></input><br>
        
        <table>
            <thead>
                <tr>
                    <th>Gen ID</th>
                    <th>Nume Gen</th>
                </tr>
            </thead>
            <tbody>
                {% for gen in genuri %}
                <tr>
                    <td>{{ gen[0] }}</td>
                    <td>{{ gen[1] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>

        <label id="dir-label"><b>Directorul filmului (introduceți id-ul):</b></label><br>
        <input name="dirName" class="transparent-button" required></input><br>

        <table>
            <thead>
                <tr>
                    <th>Director ID</th>
                    <th>Nume Prenume</th>
                </tr>
            </thead>
            <tbody>
                {% for dir in director %}
                <tr>
                    <td>{{ dir[0] }}</td>
                    <td>{{ dir[1] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        
        <label id="scen-label"><b>Scenariul filmului (introduceți id-ul):</b></label><br>
        <input name="scenName" class="transparent-button" required></input><br>

        <table>
            <thead>
                <tr>
                    <th>Scenariu ID</th>
                    <th>Nume</th>
                </tr>
            </thead>
            <tbody>
                {% for scenariu in scenarii %}
                <tr>
                    <td>{{ scenariu[0] }}</td>
                    <td>{{ scenariu[1] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>

      <input type="submit" id="submit" class="mod-button"  name="submit" value="Submit">
    </form>
  </div>
  
</body>
</html> 

website/templates/home.html
 {% block title  %}Acasă{% endblock %}


<!DOCTYPE html>
 <html>
 <head>
    
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Acasă</title> 
        <!-- Favicon-->
        <!--<link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" /> -->
        <!-- Font Awesome icons (free version)-->
        <!--<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script> -->
        <!-- Google fonts-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"> 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> 
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
            integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
            crossorigin="anonymous"
        />

        
        <link

    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" 
    crossorigin="anonymous">
    </script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="static/css/styles.css" rel="stylesheet" /> 

        <style>
            body {
            
                
              background-image: url('/static/header-bg.png');
              background-repeat: no-repeat;
              background-size: cover;
              
            }
          </style> 
         
    <br><br><br>
</head>
<body id="page-top">
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            MENU
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse justify-content-start" id="navbarResponsive">
            <div class="d-flex">  
                <ul class="navbar-nav">
                    <a class="nav-item nav-link align-self-start" id="home" href="/home">Acasă</a>
                    <a class="nav-item nav-link align-self-start" id="form" href="/formular">Formular</a>
                    <a class="nav-item nav-link align-self-start" id="form" href="/formular_rezultate">Recomandari</a>
                    <a class="nav-item nav-link align-self-start" id="form" href="/filme">Filme și Seriale</a>
                    <!-- <a class="nav-item nav-link align-self-start" id="home" href="/home">Logout</a> -->
                    
                </ul>
            </div>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive">
            <ul class="navbar-nav ">
                <!--
              <a class="nav-item nav-link" id="about" href="/about">About</a>
              <a class="nav-item nav-link "id="contact" href="/contact">Contact</a 
                
              <div style="width:150px;margin:auto;height:500px;margin-top:300px">-->

                {% if email %}
                    <li><a class="nav-item nav-link" id ="home" href="/logout">Delogare ({{ email }}) </a></li>
                {% elif not email %}
                     <li><a class="nav-item nav-link" id ="home">Nu sunteți logat! </a></li>
                {% endif %}
              

                
                
              </div>
            </ul>		  
        </div>  
    </div> 

  
 </nav>

  <!-- Masthead-->
  <header class="masthead">
    <div class="container" >
        
        <div class="masthead-subheading" style =" text-align : right; height: 20px;">Bine ați venit !</div>
        <div class="masthead-heading text-uppercase" style = " text-align : right ;font-size: 20px">Ne bucurăm să vă avem pe platforma noastră !</div>
            <div style =" text-align : right "> 
                <a id="signUp" href="/sign-up" >Nu aveți un cont? Apăsați aici!</a>
                <br>
                <a id="login" href="/login">Aveți un cont creat? Apăsați aici!</a>  
            </div>

            <br><br>
                <div class="text-left" style = "text-align : right ;font-size: 15px; margin-top : 100px">
                    <h2 class="section-heading text-uppercase" style = "font-size: 20px">Detalii de contact</h2>
                    <p> Adresă email : ofiterescumaria@gmail.com </p>
                </div>
        <!--   <a class="btn btn-primary btn-xl text-uppercase" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
        <a class="btn btn-secondary btn-xl text-uppercase" href="#services">Register</a> -->
        <!-- <a class="btn btn-primary btn-xl text-uppercase" href="#services">Sign Up</a>
            <a class="btn btn-secondary btn-xl text-uppercase" href="#serviceS">Register</a> -->
            <!--<a class="btn btn-primary btn-xl text-uppercase" href="#services">Tell Me More</a> -->
        </div>
</header>



 
  
    
</div>



</body>
    {% for item in data %}
    <p>{{item[0]}}</p>
    <p>{{item[1]}}</p>
    {% endfor %}   

   

website/templates/login.html
 {% block title  %}Login{% endblock %} 


<!DOCTYPE html>
<html>
<head>
   
       
       <meta charset="utf-8" />
       <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
       <meta name="description" content="" />
       <meta name="author" content="" />
       <title>Login</title> 
       <!-- Favicon-->
       <!--<link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" /> -->
       <!-- Font Awesome icons (free version)-->
       <!--<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script> -->
       <!-- Google fonts-->
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"> 
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
       <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
       <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" /> 
       <link
           rel="stylesheet"
           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
           integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
           crossorigin="anonymous"
       />

       
       <link

   <script
   src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
   integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" 
   crossorigin="anonymous">
   </script>
       <!-- Core theme CSS (includes Bootstrap)-->
       <link href="static/css/styles.css" rel="stylesheet" /> 
<br><br>
       <style>
           body {
           
               
             background-image: url('/static/header-bg.png');
             background-repeat: no-repeat;
             background-size: cover;
             
           }
         </style> 
        
  
</head>
  
    <body id="page-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
           <div class="container-fluid">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                MENU
                <i class="fas fa-bars ms-1"></i>
            </button>
               <div class="collapse navbar-collapse justify-content-start" id="navbarResponsive">
                   <div class="d-flex">  
                       <ul class="navbar-nav">
                           <a class="nav-item nav-link align-self-start" id="login" href="/login">Logare</a>
                           <a class="nav-item nav-link align-self-start" id="signUP" href="/sign-up">Înregistrare</a>
                           
                       </ul>
                   </div>
               </div>
               <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive">
                   <ul class="navbar-nav ">
                       
                     </div>
                   </ul>		  
               </div>  
           </div> 
        </nav>
<br>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error'%}
      <div class="alert alert-danger alert-dismissible fade show">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
         {{ message }}
        
      </div>
      {% else %}
      <div class="alert alert-success alert-dismissible fade show">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
      </div>
      {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}  

        <!-- Masthead-->
        <style>
          
      
       .masthead-subheading2 {
        font-size: 2rem;
        font-style: italic;
        line-height: 2rem;
        margin-bottom: 25px;
        margin-right: 30px;
        font-family: "Roboto Slab", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }
       .masthead-heading2 {
        font-size: 3.25rem;
        font-weight: 700;
        line-height: 3.25rem;
        margin-bottom: 2rem;
        margin-right: 30px;
        font-family: "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        }
        </style>
    <br><br>
        <div class="masthead-subheading2" style =" text-align : right;color : #fff  ">Vă rugăm să vă introduceți datele!</div>
        
            <br><br>
        <form method="POST">
            
            <div class="form-group" style =" margin-left: 900px; width: 20%;">
                <label for="email">Adresă Email</label>
                <input 
                    type="email" 
                    class="form-control" 
                    id="email" 
                    name="email" 
                    placeholder="Introduceți email"
                />
            </div>
            
        
            <div class="form-group" style =" margin-left: 900px ;  width: 20%;">
                <label for="password1">Parolă</label>
                <input 
                    type="password" 
                    class="form-control" 
                    id="password1" 
                    name="password1" 
                    placeholder="Introduceți parola"
                />

            </div>
            <br />
            <button type="submit" class="btn btn-primary" style = "margin-left: 900px;">Login</button>
        </form>

      
    <!--   <a class="btn btn-primary btn-xl text-uppercase" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
       <a class="btn btn-secondary btn-xl text-uppercase" href="#services">Register</a> -->
       <!-- <a class="btn btn-primary btn-xl text-uppercase" href="#services">Sign Up</a>
        <a class="btn btn-secondary btn-xl text-uppercase" href="#serviceS">Register</a> -->
        <!--<a class="btn btn-primary btn-xl text-uppercase" href="#services">Tell Me More</a> -->
    

    
    
</body>
</html>